# Default (false) will load mathjax / katex script on demand.
# That is it only render those page which has `mathjax: true` in Front Matter.
# If you set it to true, it will load mathjax / katex srcipt EVERY PAGE.
per_page: false

engine: mathjax
#engine: katex

# hexo-rendering-pandoc (or hexo-renderer-kramed) needed to full MathJax support.
mathjax:
  cdn: //cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  #cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

  # See: https://mhchem.github.io/MathJax-mhchem/
  #mhchem: //cdn.jsdelivr.net/npm/mathjax-mhchem@3
  #mhchem: //cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.0
